# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = 'rogers_scaffold'
  s.version = '0.1.3'

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ['Roger Heykoop']
  s.date = '2014-06-03'
  s.description = 'Rogers scaffold generator for Rails 4.1'
  s.email = 'roger@dn.nl'
  s.extra_rdoc_files = ['LICENSE.txt', 'README.rdoc']

  s.homepage = 'http://github.com/rogerheykoop/rogers_scaffold'
  s.licenses = ['GPLv2']
  s.require_paths = ['lib']
  s.rubygems_version = '1.3.7'
  s.summary = 'Rogers scaffold generator for Rails 4.1'

  s.files = Dir['{app,config,db,lib}/**/*'] + ['LICENSE.txt', 'Rakefile', 'README.rdoc']
  s.test_files = Dir['test/**/*']


end


